### PR TITLE
Update to bpmn-js-token-simulation@0.19

### LINKED ISSUE #29: Pausing of token disabled if process is modeled inside process pool
__Describe the Bug__

When I try to pause a running token simulation, the pause button is disabled if a process is modeled inside a pool element.

__Steps to Reproduce__

1. Model simple process
2. Wrap a bpm pool element around
3. Start token simulation
4. Try to use the "pause" button

__Expected Behavior__

The pause button should function the same way as it does without a pool element.

__Environment__

- Modeler: 4.7.0
- OS: [Ubuntu 20.04.2 LTS]

bug_pausing_token_inside_pool

### LINKED ISSUE #30: Play-Button is not reactivated after simulation finishes in multi pool models
__Describe the Bug__
When a BPMN contains not only multiple lanes in a single pool, even if there are multiple pools with 1 or more lanes, each process start event has a "play button". When I choose one of the events to run the simulation, it all runs fine (in the newest version with a lot more supported elements (y) ). After the simulation run is over, in nearly all scenarios of model designs all start events get back their play button. But if you have 2 or more pools in a model, only the play button of the started pool reapears. I need to shut down token simulation an start it again, then all start events are runnable again. This is what I expect after finishing too.

__Steps to Reproduce__
1.) create a new pool
2.) add a simple process to simulate in pool 1
3.) create another new pool
4.) add a simple process to simulate again in pool 2
5.) run simulation in any pool
6.) after finishing of simulation 1 try to start to simulate the other one ;)

__Expected Behavior__
I expect the same behavior like at the beginning, when i activate the plugin and set Token Simulation to green. Then all pools can be simulated.

__Environment__
Modeler 4.7.0 win-x64

Best regards
Frank

### LINKED ISSUE #31: switch at gateway does not show other pathes in grey
This on 4.8.1.8069 on OS X 10.15.7

Switching at the gateway shows no difference and the choosen path looks like the others.

Bildschirmfoto 2021-05-19 um 18 43 25

---

Depends on https://github.com/camunda/camunda-modeler/pull/2281.

### PR DESCRIPTION
**Pull request by nikku**
* Upgrade to latest token-simulation version
* House keeping (GitHub actions, `package.json#files`, dependency bumps)...
* Prepare new release

---

Closes #29
Closes #30

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
The new features are super smooth 👏  

One tiny thing, I checked the issues to be closed and the gateway paths are still don't differ in color (cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31)

Kapture 2021-05-20 at 13 12 01

**Comment by nikku** [comment]
Will investigate the not fixed gateway path thing.

**Comment by nikku** [comment]
The issue [here](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/pull/32#pullrequestreview-664248107) is that loading of styles is not properly awaited in the Camunda Modeler plug-in infrastructure, cf. [`Plugins`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/remote/Plugins.js#L41). This leads to the situation that scripts do not properly work if they require the CSS to be loaded. 

In the token-simulation plug-in case, the token simulation depends on the CSS to retrieve themed colors. The CSS being missing (not loaded yet) simply defaults to no colors being used.

**Comment by nikku** [comment]
I've excluded the mentioned issue from this PR, as it something along this line as a fix: https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/31#issuecomment-845096874.

**Review by pinussilvestrus — APPROVED** [review]

**Pull request merged**
