### PR TITLE
feat: Adding MacOS install instructions

### PR DESCRIPTION
**Pull request by davidgs**

### CODE REVIEW

**Review by pinussilvestrus — COMMENTED** [review]
Can you explain why you see it important to have such a section exclusively for macOS and not for other platforms as well?

I'd personally rather improve the [general installation section](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/README.md#how-to-use) instead of dividing it into platform-specific ones.

**Comment by davidgs** [comment]
> Can you explain why you see it important to have such a section exclusively for macOS and not for other platforms as well?

It's habit different on macOS in that finding the plugins directory is somewhat more difficult (typically both locations where it would exist are hidden from the user). 
 
> I'd personally rather improve the [general installation section](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/README.md#how-to-use) instead of dividing it into platform-specific ones.

I don't know where the plugins directory is on Linux or Windows, but I'm assuming it's in different places on each platform, so you would need a section for each for completeness.

**Comment by pinussilvestrus** [comment]
I'd keep the README as short as possible. If the installation only differs in the path for plugins directory, then maybe it's sufficient to link to the search path documentation: https://github.com/camunda/camunda-modeler/tree/master/docs/search-paths#search-paths.

Or as we do it with other plugins - reference the plugins documentation: https://github.com/pinussilvestrus/camunda-modeler-autosave-plugin#how-to-use

```text
## How to use

1. Download and copy this repository into the `plugins` directory of the Camunda Modeler
2. Start the Camunda Modeler
3. Simulate tokens in a regular BPMN tab

Refer to the [plugins documentation](https://github.com/camunda/camunda-modeler/tree/master/docs/plugins#plugging-into-the-camunda-modeler) to get detailed information on how to create and integrate Camunda Modeler plugins.
```

**Comment by davidgs** [comment]
I was just trying to be helpful and provide an easy path for installation for Mac users. Took me a while to find out where to put it, so ... 

Feel free to not accept the PR.

**Comment by pinussilvestrus** [comment]
> Hiding it behind another link that users have to click through just reduces the chances that someone will end up installing it.

That's a valid point, to be fair.

Any thoughts @bpmn-io/modeling-dev?

**Comment by nikku** [comment]
I'm O.K. with merging it, as is. 

As a follow up we could think about many ways to improve the installation. Imagine we had a simple command-line tool that is shipped with the app. I.e. `camunda-modeler --install-plugin [PLUGIN_SOURCE]`. That would be my favorite, mid-term.

Everything else is just an intermediate, not too cool solution, in my honest opinion.

**Review by pinussilvestrus — APPROVED** [review]
Well then, I'm fine. Thanks 👏

**Comment by davidgs** [comment]
A simple shell/bat script could do this pretty easily. Shell script could deal with linux/macOS and  bat script could do Windows. I'm happy to take a run at such a script if you'd like.

**Comment by nikku** [comment]
> A simple shell/bat script could do this pretty easily. 

But that would mean that people need to download that script in the first place, too, right?

So how would that one-liner look like that we add to each plug-ins `README`? Can we assume that people have `npm` installed`? I do not think so. But what we can assume is that they have the modeler downloaded and the executable on their `PATH`, somewhere, right?

**Pull request merged**
